name: Continuous Integration

on:
  push:
    branches: master
jobs:
  build-examples:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@f90c7b395dac7c5a277c1a6d93d5057c1cddb74e
    - name: Build all examples
      run: ./extras/ci/scripts/build-examples.sh
